<h2>Sign up in 2 minutes!</h2>

<?php echo $this->tag->form("signup/register"); ?>
    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <?php
        // echo $this->tag->linkTo(
        //     'Phalcon_app/tutorial/public/signup/register.phtml',  //Tag URL que vai ser encaminhado
        //     'Register!',                      //Texto apresentado
        //     'class' => 'submitButton',
        // );
        
        echo $this->tag->submitButton('Register!'); 
        ?>
        
    </p>

</form>